staging:
  host: localhost
  database: ten10_staging
  username: ten10_wp
  password: 'ten10_wp_staging'
production:
  host: localhost
  database: db_name
  username: db_user
  password: 'db_pass'
development:
  host: localhost
  database: ten10_devSrv
  username: tripl3inf
  password: 'tripl3inf'