staging:
  host: localhost
  database: ten10_staging
  username: root
  password: 'superCool$hit101'
production:
  host: localhost
  database: db_name
  username: db_user
  password: 'db_pass'
development:
  host: localhost
  database: ten10_devSrv
  username: tripl3inf
  password: 'tripl3inf'